# tcp_splice - top-level build orchestrator.
#
# The three components have distinct toolchains, each with its own Makefile:
#   module/  kbuild        -> tcp_splice.ko
#   bpf/     clang -target bpf -> splice.bpf.o (+ skeleton)
#   ctl/     host cc + libbpf  -> tcp-splice-ctl   (consumes bpf/ skeleton)

.PHONY: all module bpf ctl test clean deb

all: module bpf ctl

module:
	$(MAKE) -C module

bpf:
	$(MAKE) -C bpf

# The control tool includes the skeleton generated by bpf/, so order matters.
ctl: bpf
	$(MAKE) -C ctl

test:
	./tests/test_loopback.sh

# Package the already-built module/ctl into a .deb (fixed/appliance kernel).
# Build (make module ctl) and sign the module first; see packaging/README.md.
deb:
	sh packaging/make-deb.sh

clean:
	$(MAKE) -C module clean
	$(MAKE) -C bpf clean
	$(MAKE) -C ctl clean
