# tcp_splice - top-level build orchestrator.
#
# The three components have distinct toolchains, each with its own Makefile:
#   module/  kbuild        -> tcp_splice.ko
#   bpf/     clang -target bpf -> splice.bpf.o (+ skeleton)
#   ctl/     host cc + libbpf  -> tcp-splice-ctl   (consumes bpf/ skeleton)

.PHONY: all module bpf ctl test clean deb

all: module bpf ctl

module:
	$(MAKE) -C module

bpf:
	$(MAKE) -C bpf

# The control tool includes the skeleton generated by bpf/, so order matters.
ctl: bpf
	$(MAKE) -C ctl

# Run the data-path tests. Load the module and configure tcp-splice-ctl (so the
# tests' loopback flows are spliced) before `make test`; the tests do not.
test:
	@fail=0; \
	for t in "tests/test_loopback.py" "tests/test_bidir.py" \
	         "tests/poll.py blocking" "tests/poll.py select" \
	         "tests/churn.py"; do \
		echo "==> $$t"; \
		python3 $$t || fail=1; \
	done; \
	if [ $$fail -ne 0 ]; then echo "make test: FAILED" >&2; exit 1; fi; \
	echo "make test: all passed"

# Package the already-built module/ctl into a .deb (fixed/appliance kernel).
# Build (make module ctl) and sign the module first; see packaging/README.md.
deb:
	sh packaging/make-deb.sh

clean:
	$(MAKE) -C module clean
	$(MAKE) -C bpf clean
	$(MAKE) -C ctl clean
